mkdir config
nano config/suricata.yaml
#example

# config/suricata.yaml
HOME_NET: "[192.168.1.0/24]"
EXTERNAL_NET: "any"

default-rule-path: /etc/suricata/rules
rule-files:
  - botcc.rules
  - ciarmy.rules
  - emerging-exploit.rules
  - emerging-malware.rules

af-packet:
  - interface: eth0
    cluster-id: 98
    cluster-type: cluster_flow

logging:
  outputs:
    - fast:
        enabled: yes
        filename: fast.log
    - eve-log:
        enabled: yes
        filetype: regular
        filename: eve.json
        types:
          - alert
          - http
          - dns
          - tls
